# Generated by Django 3.2.20 on 2023-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprompt',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
