# Generated by Django 3.2.23 on 2024-01-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0005_learningassistantcourseenabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePrompt',
        ),
    ]
