# Generated by Django 4.2.18 on 2025-02-12 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0009_learningassistantaudittrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningassistantaudittrial',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 0, 0)),
        ),
    ]
